SELECT REST_INFO.FOOD_TYPE, REST_INFO.REST_ID, REST_INFO.REST_NAME, REST_INFO.FAVORITES
FROM REST_INFO JOIN (
        SELECT MAX(FAVORITES) FAVORITES, FOOD_TYPE
        FROM REST_INFO
        GROUP BY FOOD_TYPE
    ) FAVORITES_INFO
ON REST_INFO.FOOD_TYPE = FAVORITES_INFO.FOOD_TYPE 
AND REST_INFO.FAVORITES = FAVORITES_INFO.FAVORITES
ORDER BY FOOD_TYPE DESC
