SELECT INFO.REST_ID, 
       REST_NAME, 
       FOOD_TYPE, 
       FAVORITES, 
       ADDRESS, 
       SCORE
FROM REST_INFO INFO, (SELECT REST_ID, ROUND(AVG(REVIEW_SCORE), 2) AS SCORE
                      FROM REST_REVIEW
                      GROUP BY REST_ID) REVIEW
WHERE INFO.REST_ID = REVIEW.REST_ID AND ADDRESS LIKE '서울%'
ORDER BY REVIEW.SCORE DESC, FAVORITES DESC