SELECT AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY, SUM(SALES * PRICE)
FROM BOOK, AUTHOR, BOOK_SALES
WHERE TO_CHAR(BOOK_SALES.SALES_DATE, 'YYYYMM') = '202201' 
      AND BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
      AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
GROUP BY AUTHOR.AUTHOR_ID, AUTHOR.AUTHOR_NAME, BOOK.CATEGORY
ORDER BY AUTHOR.AUTHOR_ID, BOOK.CATEGORY DESC
