SELECT A.HISTORY_ID, (DAILY_FEE * RENT_DAY) * (100 - NVL(DISCOUNT_RATE, 0)) / 100 AS FEE
FROM (
    SELECT HISTORY_ID, CAR.CAR_ID, CAR_TYPE, DAILY_FEE, (END_DATE - START_DATE + 1) AS RENT_DAY,
      CASE WHEN END_DATE - START_DATE + 1 BETWEEN 7 AND 29 THEN '7일 이상'
           WHEN END_DATE - START_DATE + 1 BETWEEN 30 AND 89 THEN '30일 이상'
           WHEN (END_DATE - START_DATE + 1) >= 90 THEN '90일 이상'
      END AS DURATION_TYPE
      FROM CAR_RENTAL_COMPANY_CAR CAR JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY HISTORY
      ON CAR.CAR_ID = HISTORY.CAR_ID
      WHERE CAR.CAR_TYPE = '트럭'
) A
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN B
ON A.CAR_TYPE = B.CAR_TYPE AND A.DURATION_TYPE = B.DURATION_TYPE
WHERE A.CAR_TYPE = '트럭'
ORDER BY FEE DESC, A.HISTORY_ID DESC