SELECT ('/home/grep/src/' || BOARD.BOARD_ID || '/' || FILES.FILE_ID || FILES.FILE_NAME || FILES.FILE_EXT) PATH
FROM USED_GOODS_BOARD BOARD JOIN USED_GOODS_FILE FILES
ON BOARD.BOARD_ID = FILES.BOARD_ID
WHERE BOARD.VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)
ORDER BY FILES.FILE_ID DESC