SELECT A.ANIMAL_ID, A.NAME
FROM (SELECT OUTS.ANIMAL_ID, OUTS.NAME
      FROM ANIMAL_INS INS RIGHT OUTER JOIN ANIMAL_OUTS OUTS
      ON OUTS.ANIMAL_ID = INS.ANIMAL_ID
      WHERE INS.ANIMAL_ID IS NULL
     ) A
ORDER BY A.ANIMAL_ID