SELECT NAME, DATETIME
FROM (SELECT INS.ANIMAL_ID, INS.DATETIME, INS.NAME, RANK() OVER (ORDER BY INS.DATETIME) RANKED
    FROM ANIMAL_INS INS LEFT JOIN ANIMAL_OUTS OUTS
    ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
    WHERE OUTS.DATETIME IS NULL) A
WHERE A.RANKED < 4
ORDER BY DATETIME