SELECT ANIMAL_ID, NAME
FROM (SELECT INS.ANIMAL_ID, INS.NAME, RANK() OVER (ORDER BY (OUTS.DATETIME - INS.DATETIME) DESC) RANK
      FROM ANIMAL_INS INS JOIN ANIMAL_OUTS OUTS
      ON INS.ANIMAL_ID = OUTS.ANIMAL_ID) RANKED
WHERE RANKED.RANK BETWEEN 1 AND 2
ORDER BY RANK